name: Josh Galt
favicon: null
layout_spectrum: 0.26436
typography_spectrum: 0.24778
title: 'Artist, athlete, & entrepreneur chasing sunshine & h2o'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8de01'
    - '#fd0100'
    - '#009300'
    - '#121212'
    - '#cb7601'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
